services:
#    symfochess_parties.example:
#        class: Symfochess\PartiesBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    symfochess_parties.gestion:
        class: Symfochess\PartiesBundle\Services\GestionParties
        arguments: [@templating, @mailer, @security.context, @doctrine.orm.entity_manager]