<?php

namespace Symfochess\PartiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartieRepository extends EntityRepository
{
    /**
     * @param $idPartie
     *
     * On récupère toutes les invitations de la partie
     */
    public function getInvitations(\Symfochess\PartiesBundle\Entity\Partie $partie)
    {
        return $this->getEntityManager()
            ->createQuery('
                SELECT i FROM SymfochessJoueurBundle:Invitation i WHERE i.partie = :partie
            ')
            ->setParameter('partie', $partie)
            ->getResult();
    }

    /**
     * @param $idPartie
     *
     * On récupère toutes les invitations de la partie
     */
    public function compteInvitationsNonAcceptees(\Symfochess\PartiesBundle\Entity\Partie $partie)
    {
        return (int)$this->getEntityManager()
            ->createQuery("
                SELECT count(i.id) FROM SymfochessJoueurBundle:Invitation i WHERE i.etat != 'AC' and i.partie = :partie
            ")
            ->setParameter('partie', $partie)
            ->getSingleScalarResult();
    }
}
